# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52c58049a18f33ea72c407f40467bdcdeee2a01fc0e90638d17f2118dc4a552325d251f6f98610fd66dfb9b07c35c0cbab2e65eb58899fa0ce35cfc52dae5fff

test:
  secret_key_base: 9d73f73f1047998941bb841cca612315034ec99757f6473acbac4247c6881b33a53f04419cca7874dbc025d0cb1afb26875a38649a4f3d473b3bd754daa8e81c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
